<a href="https://colab.research.google.com/github/IvanovArtem07/Numpy_solutions/blob/main/Numpy_solutions_%D0%9F%D1%80%D0%BE%D0%BC%D0%B5%D0%B6%D1%83%D1%82%D0%BE%D1%87%D0%BD%D0%B0%D1%8F_%D0%B0%D1%82%D1%82%D0%B5%D1%81%D1%82%D0%B0%D1%86%D0%B8%D1%8F_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2_%D0%90%D1%80%D1%82%D0%B5%D0%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a) Импортировать библиотеку NumPy

In [13]:
import numpy as np


b) Создать массив из 10 нулей

In [18]:
b=np.zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


c) Создать массив из 10 едениц

In [19]:
c=np.ones(10)
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


d) Создать массив из 10 пятерок

In [20]:
d=np.zeros(10)
d[:]=5
print(d)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


e) Создать массив из целых чисел от 10 до 50

In [21]:
e=np.arange(10, 51)
print(e)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


f) Создать массив из четных чисел от 10 до 50

In [22]:
f=np.arange(10, 51, 2)
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


g) Создать матрицу 3х3 с числами от 0 до 8

In [23]:
g=np.arange(9).reshape(3,3)
print(g)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


h) Создать еденичную матрицу 3х3

In [3]:
h=np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


i) Использовать NumPy для генерации случайного числа от 0 до 1

In [24]:
i=np.random.rand()
print(i)

0.5184608309462643


j) Использовать NumPy для генерации массива из 25 случайных чисел, 
взятого из стандартного нормального распределения

In [25]:
j=np.random.randn(25)
print(j)

[-0.29381429  1.80493244  0.45119152 -1.76049413  0.1090889   0.26478234
 -1.52001209 -0.84563218  1.43511278 -0.47628998 -1.13730234  0.29125505
  0.19793146 -0.2076495  -1.25021199 -0.41111333  0.07686298  0.85591182
  0.6621761  -0.23617413  1.77309296  0.22426926  1.66952253  1.59761556
  1.79298598]


k) Создать матрицу используя функцию библиотеки NumPy

In [26]:
k=np.linspace(0.01, 1., 100).reshape(10, 10)
print(k)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


Cтартовая матрица

In [4]:
mat=np.arange(1, 26).reshape(5, 5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


l) Необходимо написать код который вернет следующую матрицу из стартовой

In [5]:
l=mat[2:, 1:]
print(l)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


m) Написать код обращения к элементу который вернет значение  20 изстартовой матрицы.

In [6]:
m=mat[mat == 20]
print(m)

[20]


n) Написать код к стартовой матрице, который воспроизводит вывод

In [7]:
n=mat[:3, 1].reshape(3, 1)
print(n)

[[ 2]
 [ 7]
 [12]]


o) Написать код к стартовой матрице, который воспроизводит вывод

In [8]:
o=mat[4:]
print(o)

[[21 22 23 24 25]]


p) Написать код к стартовой матрице, который воспроизводит вывод

In [9]:
p=mat[3:]
print(p)

[[16 17 18 19 20]
 [21 22 23 24 25]]


q) Получить сумму всех значений в стартовой матрице mat

In [10]:
q=mat.sum()
print(q)

325


r) Получить стандартное отклонение в стартовой матрице mat

In [11]:
r=mat.std()
print(r)

7.211102550927978


s) Получить сумму значений в колонках в стартовой матрице mat

In [17]:
s=mat.sum(axis=0)
print(s)

[55 60 65 70 75]
